AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CV parser - S3 → Lambda → Textract (async PDF) → DynamoDB → DynamoDB Stream → Bedrock role matching

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 120        # give enough time for Textract async job
    MemorySize: 512

Resources:
  CVBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  CandidatesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: candidateId
          AttributeType: S
      KeySchema:
        - AttributeName: candidateId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_IMAGE   # enable DynamoDB Stream with new item image

  ResumeProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref CandidatesTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CandidatesTable
        - Statement:
            # Textract async permissions
            - Effect: Allow
              Action:
                - textract:StartDocumentTextDetection
                - textract:GetDocumentTextDetection
              Resource: "*"
            # Lambda can read from any S3 bucket (simplifies demo, avoids circular deps)
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource: "arn:aws:s3:::*"
      Events:
        CVUploadEvent:
          Type: S3
          Properties:
            Bucket: !Ref CVBucket
            Events: s3:ObjectCreated:*

  RoleMatchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: roleMatch.handler
      Timeout: 60
      MemorySize: 512
      Environment:
        Variables:
          TABLE_NAME: !Ref CandidatesTable
          ROLE_DESCRIPTION: |
            Senior Backend Engineer
            Tech: Java 17, Spring Boot, AWS, Kafka, Microservices
            Experience: 6–12 years
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CandidatesTable
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
              Resource: "*"
      Events:
        NewCandidateEvent:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt CandidatesTable.StreamArn
            StartingPosition: LATEST
            BatchSize: 1
            Enabled: true

Outputs:
  CVBucketName:
    Description: S3 bucket for uploading CVs
    Value: !Ref CVBucket

  CandidatesTableName:
    Description: DynamoDB table storing parsed candidates
    Value: !Ref CandidatesTable

  ResumeProcessorFunctionArn:
    Description: Lambda function ARN (Textract + parsing)
    Value: !GetAtt ResumeProcessorFunction.Arn

  RoleMatchFunctionArn:
    Description: Lambda function ARN (Bedrock role matching)
    Value: !GetAtt RoleMatchFunction.Arn